kind: Deployment
apiVersion: apps/v1
metadata:
  name: identity-api-deployment
  namespace: evolution
  annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "identity"
    dapr.io/app-port: "80"
    dapr.io/config: "tracing"
spec:
  selector:
    matchLabels:
      app: identity-api
  replicas: 2
  template:
    spec:
      containers:
        - name: identity-api
          env: 
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production" 
    