apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: identity-api
  namespace: evolution
spec:
  endpoints:
  - interval: 30s
    port: identity-api-port
    path: /metrics-text
  selector:
    matchLabels:
      app: identity-api