apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-nginx-ingress
  namespace: evolution
  annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: 'true'
  labels:
    name: identity-nginx-ingress  
spec:
  rules:
  - host: acme.com
    http:
      paths:
      - path: /auth/connect/token
        pathType: Prefix
        backend:
          service:
            name: identityservice-api-cluster-ip
            port: 
              number: 80
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: identityservice-api-cluster-ip
            port: 
              number: 80
