apiVersion: v1
kind: Service
metadata:
  name: identity-api-cluster-ip
  namespace: evolution
spec:
  type: ClusterIP
  selector:
    app: identity-api
  ports:
  - name: identity-api-port
    protocol: TCP
    port: 80
    targetPort: 80
