apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: identity-api
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: identity-api-port
  selector:
    matchLabels:
      app: identity-api