name: .NET

on:
  push:
    branches: [main, staging, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    if: github.ref != 'refs/heads/main'
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Check Numbers
        run: |
          echo ${{ github.run_id }}
          echo ${{ github.run_number  }}
          echo ${{ github.run_attempt  }}

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        id: dotnetrestore
        run: dotnet restore

      - if: steps.dotnetrestore.outputs.exit_code == 0
        name: Build
        id: dotnetbuild 
        run: dotnet build --no-restore

      - if: steps.dotnetbuild.outputs.exit_code == 0
        id: dotnettest
        name: Run Tests
        run: dotnet test --no-build --verbosity normal

  build-container:
    if: github.ref == 'refs/heads/main' 
    name: Docker Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Check Numbers
        run: |
          echo ${{ github.run_id }}
          echo ${{ github.run_number  }}
          echo ${{ github.run_attempt  }}

      - name: docker build
        run: |
          docker build ./src/IdentityService.Api -t rohitrustagi007/evo_identity:${{ github.run_number  }}
      
      - name : docker push
        run: |
          docker push rohitrustagi007/evo_identity:${{ github.run_number  }}
      

  # build-container:
  #   if: github.ref == 'refs/heads/main'
  #   name: Build Container Image for Identity Service API
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v3
  #     - name: Publish to Github
  #       uses: docker/build-push-action@v1
  #       with:
  #         username: ${{github.actor}}
  #         password: ${{secrets.GITHUB_TOKEN}}
  #         registry: docker.pkg.github.com
  #         repository: ${{github.repository}}/next
  #         tags: latest,${{github.run_number}}
